apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stanovanjska-kriza
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: stanovanjska-kriza
    newName: rg.fr-par.scw.cloud/djnd/stanovanjska-kriza
    newTag: 'ef8bbdef37115f2cb424719207ddb2c5d85c14bc'
